### ISSUE TITLE
Remove footer relative positioning

### ISSUE THREAD

**Issue by TimelikeClosure** [TimelikeClosure/mboutique#11]
Remove relative positioning inside footer (perhaps turning .social-media into its own flexbox).

**Comment by Deg5112** [comment]
Are u reviewing every project of mine or just mboutique?

**Comment by TimelikeClosure** [comment]
@Deg5112 Just my mboutique project.  Dan was showing me how to put in issues so I could back to them later.  Should I close these and just keep track of them some other way?

**Comment by TimelikeClosure** [comment]
This project is no longer supported.
